---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-consumer-service
  template:
    metadata:
      labels:
        app: config-consumer-service
    spec:
      containers:
        - name: config-consumer-service
          image: ericm24/config-consumer-service:k8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 70
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: config-service-consumer-lb
spec:
  type: LoadBalancer
  selector:
    app: config-consumer-service
  ports:
    - port: 8080
      targetPort: 8080