spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # URI of GIT repo containing properties
          uri: https://github.com/ericm48/spring-config-server-on-kubernettes
          #uri: https://github.com/briansjavablog/spring-config-server-on-kubernettes
          default-label: main
          search-paths: configuration
          refresh-rate: 5
          skipSslValidation: true
server:
  port: 8888
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"