spring:
  application:
    name: config-server
  profiles:
    active: native    
  cloud:
    config:
      server:
        native:
          search-locations:
          - /tmp/config-server-fileshare

#        git:
#          # URI of GIT repo containing properties
#          uri: https://github.com/ericm48/spring-config-server-on-kubernettes          
#          default-label: main
#          search-paths: configuration
#          refresh-rate: 5          
server:
  port: 8888
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"